"use client";

import { useState, useCallback } from "react";
import Link from "next/link";
import { CANONICAL_HOST } from "@/lib/origin";

type Role = {
  id: string;
  label: string;
  wallet: string;
  pct: number;
};

const DEFAULT_ROLES: Role[] = [
  { id: "r1", label: "Artist", wallet: "", pct: 70 },
  { id: "r2", label: "Producer", wallet: "", pct: 20 },
  { id: "r3", label: "Community pool", wallet: "", pct: 8 },
  { id: "r4", label: "Treasury", wallet: "", pct: 2 },
];

let nextId = 5;
function uid() {
  return `r${nextId++}`;
}

function total(roles: Role[]) {
  return roles.reduce((s, r) => s + r.pct, 0);
}

function toSplitsJson(roles: Role[], projectName: string) {
  const recipients = roles
    .filter((r) => r.pct > 0 && r.wallet)
    .map((r) => ({
      address: r.wallet,
      percentAllocation: r.pct,
    }));
  return JSON.stringify(
    {
      _comment:
        `Split sheet for ${projectName || "Untitled project"} - generated by Sparkz (${CANONICAL_HOST}/split-wizard). ` +
        "Paste into app.splits.org → Create Split. Set as Clanker fee recipient.",
      distributorFeePercent: 0,
      recipients,
    },
    null,
    2
  );
}

function toMarkdown(roles: Role[], projectName: string, notes: string) {
  const lines = [
    `# Split sheet - ${projectName || "Untitled project"}`,
    "",
    `> Generated by Sparkz (${CANONICAL_HOST}/split-wizard)`,
    `> IPFS-attestable: upload this file to IPFS and save the CID as your on-chain record.`,
    "",
    "## Allocation",
    "",
    "| Role | Address | % |",
    "|------|---------|---|",
    ...roles.map((r) => `| ${r.label} | ${r.wallet || " - "} | ${r.pct}% |`),
    "",
    `**Total: ${total(roles)}%**`,
    "",
    "## Notes",
    "",
    notes || " - ",
    "",
    "## Terms",
    "",
    "- All allocations are of the 0xSplits community pool, NOT the total creator revenue",
    "- Recipients claim at splits.org - pull model, no deadline, no auto-payout",
    "- The 0xSplits contract address must be set as the Clanker fee recipient at deploy",
    "- Split weights are adjustable on-chain by the contract controller after deploy",
    "- This document is IPFS-attestable: the CID is the immutable record of agreement",
  ];
  return lines.join("\n");
}

export default function SplitWizardPage() {
  const [projectName, setProjectName] = useState("");
  const [notes, setNotes] = useState("");
  const [roles, setRoles] = useState<Role[]>(DEFAULT_ROLES);
  const [exported, setExported] = useState<"json" | "md" | null>(null);
  const [copied, setCopied] = useState(false);

  const sum = total(roles);
  const valid = sum === 100;

  const updateRole = useCallback((id: string, field: keyof Role, value: string | number) => {
    setRoles((rs) =>
      rs.map((r) => (r.id === id ? { ...r, [field]: value } : r))
    );
  }, []);

  const addRole = useCallback(() => {
    setRoles((rs) => [...rs, { id: uid(), label: "", wallet: "", pct: 0 }]);
  }, []);

  const removeRole = useCallback((id: string) => {
    setRoles((rs) => rs.filter((r) => r.id !== id));
  }, []);

  const exportContent = exported === "json" ? toSplitsJson(roles, projectName) : toMarkdown(roles, projectName, notes);

  const copyToClipboard = useCallback(async () => {
    await navigator.clipboard.writeText(exportContent);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  }, [exportContent]);

  const downloadFile = useCallback(() => {
    const ext = exported === "json" ? "json" : "md";
    const blob = new Blob([exportContent], { type: "text/plain" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = `split-sheet-${(projectName || "untitled").toLowerCase().replace(/\s+/g, "-")}.${ext}`;
    a.click();
    URL.revokeObjectURL(url);
  }, [exportContent, projectName, exported]);

  return (
    <main className="mx-auto w-full max-w-2xl flex-1 px-4">
      {/* Hero */}
      <section className="pt-14 pb-8">
        <p className="mb-3 text-xs font-medium uppercase tracking-widest text-accent">
          Split-sheet wizard
        </p>
        <h1 className="text-4xl font-semibold leading-tight tracking-tight sm:text-5xl">
          Set the split before you launch.
        </h1>
        <p className="mt-4 text-lg text-muted">
          Define who gets what - before the token drops. IPFS-attest the sheet, wire it to 0xSplits. The music-native way to kill revenue disputes before they start.
        </p>
        <div className="mt-3 flex flex-wrap gap-2 text-xs text-muted">
          <span className="rounded-full border border-border px-2 py-0.5">✓ IPFS-attestable</span>
          <span className="rounded-full border border-border px-2 py-0.5">✓ Exports 0xSplits JSON</span>
          <span className="rounded-full border border-border px-2 py-0.5">✓ No data sent to Sparkz</span>
        </div>
      </section>

      {/* Project name */}
      <section className="border-t border-border py-6">
        <label className="mb-2 block text-sm font-medium">
          Project name
        </label>
        <input
          className="w-full rounded-lg border border-border bg-card px-3 py-2 text-sm focus:border-accent focus:outline-none"
          placeholder="e.g. CoCConcertZ collab single"
          value={projectName}
          onChange={(e) => setProjectName(e.target.value)}
        />
      </section>

      {/* Roles */}
      <section className="border-t border-border py-6">
        <div className="mb-4 flex items-center justify-between">
          <span className="text-sm font-medium">Roles &amp; allocations</span>
          <span
            className={`text-sm font-semibold ${valid ? "text-green-400" : sum > 100 ? "text-red-400" : "text-accent"}`}
          >
            {sum}% {valid ? "✓" : sum > 100 ? "(over 100)" : `(${100 - sum}% remaining)`}
          </span>
        </div>

        {/* Visual bar */}
        <div className="mb-4 flex h-3 w-full overflow-hidden rounded-full bg-surface">
          {roles.map((r, i) => (
            <div
              key={r.id}
              style={{
                width: `${Math.min(r.pct, 100)}%`,
                backgroundColor: `hsl(${(i * 67) % 360}, 70%, 55%)`,
              }}
              title={`${r.label}: ${r.pct}%`}
            />
          ))}
        </div>

        <div className="space-y-2">
          {roles.map((r) => (
            <div key={r.id} className="glass flex items-center gap-2 p-3">
              <div className="flex flex-1 flex-wrap gap-2">
                <input
                  className="min-w-0 flex-1 rounded border border-border bg-card px-2 py-1 text-sm focus:border-accent focus:outline-none"
                  placeholder="Role (e.g. Artist)"
                  value={r.label}
                  onChange={(e) => updateRole(r.id, "label", e.target.value)}
                />
                <input
                  className="min-w-0 flex-[2] rounded border border-border bg-card px-2 py-1 font-mono text-xs focus:border-accent focus:outline-none"
                  placeholder="0x wallet address (optional)"
                  value={r.wallet}
                  onChange={(e) => updateRole(r.id, "wallet", e.target.value)}
                />
                <div className="flex items-center gap-1">
                  <input
                    className="w-16 rounded border border-border bg-card px-2 py-1 text-right text-sm focus:border-accent focus:outline-none"
                    type="number"
                    min={0}
                    max={100}
                    value={r.pct}
                    onChange={(e) => updateRole(r.id, "pct", Number(e.target.value))}
                  />
                  <span className="text-sm text-muted">%</span>
                </div>
              </div>
              <button
                onClick={() => removeRole(r.id)}
                className="shrink-0 text-muted/50 hover:text-red-400 transition-colors text-lg leading-none"
                aria-label="Remove role"
              >
                ×
              </button>
            </div>
          ))}
        </div>

        <button
          onClick={addRole}
          className="mt-3 text-sm text-accent hover:underline"
        >
          + Add role
        </button>
      </section>

      {/* Notes */}
      <section className="border-t border-border py-6">
        <label className="mb-2 block text-sm font-medium">Notes (optional)</label>
        <textarea
          className="w-full rounded-lg border border-border bg-card px-3 py-2 text-sm focus:border-accent focus:outline-none"
          rows={3}
          placeholder="Any agreements, conditions, or context to include in the sheet…"
          value={notes}
          onChange={(e) => setNotes(e.target.value)}
        />
      </section>

      {/* Export */}
      <section className="border-t border-border py-6">
        <h2 className="mb-4 text-sm font-medium uppercase tracking-wide text-muted">
          Export
        </h2>
        <div className="flex flex-wrap gap-2 mb-4">
          <button
            onClick={() => setExported("json")}
            className={`rounded-lg border px-4 py-2 text-sm font-medium transition-colors ${
              exported === "json"
                ? "border-accent bg-accent/10 text-accent"
                : "border-border hover:border-accent/50"
            }`}
          >
            0xSplits JSON
          </button>
          <button
            onClick={() => setExported("md")}
            className={`rounded-lg border px-4 py-2 text-sm font-medium transition-colors ${
              exported === "md"
                ? "border-accent bg-accent/10 text-accent"
                : "border-border hover:border-accent/50"
            }`}
          >
            Markdown split sheet
          </button>
        </div>

        {exported && (
          <div className="space-y-2">
            <pre className="overflow-x-auto rounded-lg border border-border bg-surface p-4 text-xs leading-relaxed text-muted">
              {exportContent}
            </pre>
            <div className="flex gap-2">
              <button
                onClick={copyToClipboard}
                className="btn-spark rounded-lg px-4 py-2 text-sm font-semibold"
              >
                {copied ? "Copied!" : "Copy"}
              </button>
              <button
                onClick={downloadFile}
                className="rounded-lg border border-border px-4 py-2 text-sm hover:border-accent/50 transition-colors"
              >
                Download
              </button>
            </div>
            {exported === "json" && (
              <p className="text-xs text-muted">
                Paste into{" "}
                <a href="https://app.splits.org" target="_blank" rel="noreferrer" className="text-accent hover:underline">
                  app.splits.org
                </a>{" "}
                → Create Split. Set the resulting contract as your Clanker fee recipient.
              </p>
            )}
            {exported === "md" && (
              <p className="text-xs text-muted">
                Upload to IPFS (e.g.{" "}
                <a href="https://web3.storage" target="_blank" rel="noreferrer" className="text-accent hover:underline">
                  web3.storage
                </a>
                {" "}or{" "}
                <a href="https://pinata.cloud" target="_blank" rel="noreferrer" className="text-accent hover:underline">
                  pinata.cloud
                </a>
                ) and save the CID - that&apos;s your immutable record of the agreement.
              </p>
            )}
          </div>
        )}
      </section>

      {/* Next steps */}
      <section className="border-t border-border py-6">
        <div className="card-solid p-5">
          <div className="mb-1 text-xs font-medium uppercase tracking-widest text-accent">
            After the split sheet
          </div>
          <ol className="mt-3 space-y-2 text-sm text-muted">
            <li className="flex gap-2"><span className="font-semibold text-foreground/80">1.</span> Deploy the 0xSplits contract at <a href="https://app.splits.org" target="_blank" rel="noreferrer" className="text-accent hover:underline">app.splits.org</a></li>
            <li className="flex gap-2"><span className="font-semibold text-foreground/80">2.</span> Copy the contract address</li>
            <li className="flex gap-2"><span className="font-semibold text-foreground/80">3.</span> Set it as the fee recipient when deploying on <a href="https://clanker.world" target="_blank" rel="noreferrer" className="text-accent hover:underline">clanker.world</a></li>
            <li className="flex gap-2"><span className="font-semibold text-foreground/80">4.</span> Recipients claim their share anytime at <a href="https://app.splits.org" target="_blank" rel="noreferrer" className="text-accent hover:underline">app.splits.org</a> - pull model, no deadline</li>
          </ol>
        </div>
      </section>

      {/* Cross-links */}
      <section className="border-t border-border py-6">
        <div className="grid gap-2 sm:grid-cols-2">
          <Link href="/advisor" className="glass glass-hover p-3">
            <div className="font-medium text-sm">Not sure on percentages?</div>
            <div className="text-xs text-muted">Split advisor → 3 questions → recommendation</div>
          </Link>
          <Link href="/examples" className="glass glass-hover p-3">
            <div className="font-medium text-sm">See example splits</div>
            <div className="text-xs text-muted">7 templates: collab, crowdfund, solo &amp; more</div>
          </Link>
        </div>
      </section>

      <footer className="border-t border-border py-8 text-xs text-muted">
        Split sheets are generated client-side. No data is sent to Sparkz servers. IPFS attestation is a manual step.
      </footer>
    </main>
  );
}
