import type { Metadata } from "next";
import Link from "next/link";
import { canonicalOrigin, CANONICAL_HOST } from "@/lib/origin";

const BASE = canonicalOrigin();
const OG = `${BASE}/api/og?title=${encodeURIComponent("The Hearth")}&subtitle=${encodeURIComponent("Identity · backers · receipts - before any token")}`;

export const metadata: Metadata = {
  title: "The Hearth - Sparkz",
  description:
    "A Hearth is the core Sparkz entity: identity, backers, boosts, meme receipts, Farcaster identity, economic config. The community lives here before any token exists.",
  openGraph: {
    title: "The Hearth - Sparkz",
    description:
      "Identity, backers, receipts, and fee config - all before a token. The Hearth is where community starts.",
    url: `${BASE}/hearth`,
    images: [{ url: OG, width: 1200, height: 630, alt: "The Hearth - Sparkz" }],
    type: "website",
  },
  twitter: {
    card: "summary_large_image",
    title: "The Hearth - Sparkz",
    description: "The Sparkz core entity: identity + backers + receipts before any token.",
    images: [OG],
  },
  other: {
    "fc:miniapp": "true",
    "fc:frame": "vNext",
    "fc:frame:image": OG,
    "fc:frame:button:1": "🔥 Open a Hearth",
    "fc:frame:button:1:action": "link",
    "fc:frame:button:1:target": `${BASE}/start`,
    "fc:frame:button:2": "🔍 Browse Hearths",
    "fc:frame:button:2:action": "link",
    "fc:frame:button:2:target": `${BASE}/explore`,
  },
};

const FIELDS = [
  { label: "Name", desc: "The community or creator name." },
  { label: "Bio", desc: "What it's about. One paragraph, culture-first." },
  { label: "Type", desc: "creator / culture / oss / meme - sets the context for ZAO review." },
  { label: "Status", desc: "spark → tokenized → dormant. Most stay at spark." },
  { label: "Backers", desc: "Fans and supporters who backed the Hearth with a free boost." },
  { label: "Boosts", desc: "Community boosts - signal and social proof. Anyone can boost." },
  { label: "Meme receipts", desc: "Proof-of-contribution posts generated by the Meme Engine. On-chain attribution." },
  { label: "Farcaster identity", desc: "FID + Warpcast handle. Enables SIWE and Warpcast miniapp embedding." },
  { label: "ZAO review state", desc: "pending / approved / rejected. ZAO reviews every self-serve submission." },
  { label: "Economic config", desc: "The 0xSplits split: community % / creator % / treasury %. Default: 1/1/98." },
];

const LIFECYCLE = [
  {
    stage: "Spark",
    desc: "A creator opens a Hearth. ZAO reviews and approves. First backers appear. Boosts and Meme Engine receipts accumulate. No token.",
    icon: "🔥",
    color: "text-accent",
  },
  {
    stage: "Tokenized",
    desc: "The creator launches a token on Clanker (optional). Fee allocation activates via 0xSplits. Weekly split update possible. The community now earns from every trade.",
    icon: "🪙",
    color: "text-foreground",
  },
  {
    stage: "Dormant",
    desc: "The community has gone quiet. The Hearth is preserved. The creator can re-spark at any time.",
    icon: "💤",
    color: "text-muted",
  },
];

export default function HearthPage() {
  return (
    <main className="mx-auto max-w-2xl px-4 py-16 space-y-14">
      {/* Header */}
      <section>
        <p className="text-accent text-sm font-semibold mb-3 uppercase tracking-wider">
          Core concept
        </p>
        <h1 className="text-4xl font-bold mb-4">The Hearth</h1>
        <p className="text-muted text-lg leading-relaxed">
          A Hearth is where a Sparkz community lives - before any token exists.
          Identity, backers, boosts, Meme Engine receipts, Farcaster identity,
          economic config. The culture starts here.
        </p>
        <p className="text-muted text-sm mt-3">
          A token is the Hearth&rsquo;s optional economic output, not its starting point.
          Most Hearths stay tokenless - that&rsquo;s a feature, not a limitation.
        </p>
      </section>

      {/* What's in a Hearth */}
      <section>
        <h2 className="text-xl font-bold mb-5">What&rsquo;s inside a Hearth</h2>
        <div className="card-solid border border-border rounded-2xl divide-y divide-border">
          {FIELDS.map(({ label, desc }) => (
            <div key={label} className="px-5 py-3">
              <div className="flex items-baseline gap-3">
                <span className="font-semibold text-sm w-32 shrink-0">{label}</span>
                <span className="text-muted text-sm">{desc}</span>
              </div>
            </div>
          ))}
        </div>
      </section>

      {/* Lifecycle */}
      <section>
        <h2 className="text-xl font-bold mb-5">Hearth lifecycle</h2>
        <div className="space-y-4">
          {LIFECYCLE.map((l) => (
            <div key={l.stage} className="card-solid border border-border rounded-xl p-5 flex gap-4">
              <span className="text-2xl shrink-0">{l.icon}</span>
              <div>
                <div className={`font-bold text-sm mb-1 ${l.color}`}>{l.stage}</div>
                <div className="text-muted text-xs leading-relaxed">{l.desc}</div>
              </div>
            </div>
          ))}
        </div>
        <p className="text-xs text-muted mt-4 leading-relaxed">
          Token is NOT required to advance beyond Spark. Many Hearths stay tokenless
          and thrive. The community pull determines when (or whether) to tokenize.
        </p>
      </section>

      {/* Hearth at /c/[slug] */}
      <section className="card-solid border border-border rounded-2xl p-6">
        <h2 className="font-bold text-lg mb-3">
          Each Hearth lives at{" "}
          <code className="text-accent text-base font-mono">/c/[slug]</code>
        </h2>
        <p className="text-muted text-sm leading-relaxed mb-4">
          Every approved Hearth gets a public page at{" "}
          <span className="font-mono text-xs">{CANONICAL_HOST}/c/[slug]</span> - identity,
          boost button, Meme Engine receipts, backers list, graduation panel, and Farcaster
          Mini App embed. Browse the directory at{" "}
          <Link href="/explore" className="text-accent hover:underline">
            /explore
          </Link>
          .
        </p>
        <div className="flex flex-wrap gap-3">
          <Link
            href="/explore"
            className="text-sm px-4 py-2 border border-border rounded-lg text-muted hover:text-foreground hover:border-border/80 transition-colors"
          >
            🔍 Browse Hearths →
          </Link>
          <a
            href="https://zoostr.xyz"
            target="_blank"
            rel="noreferrer"
            className="text-sm px-4 py-2 border border-border rounded-lg text-muted hover:text-foreground hover:border-border/80 transition-colors"
          >
            ⚡ Zoostr live example ↗
          </a>
        </div>
      </section>

      {/* Economics default */}
      <section>
        <h2 className="text-xl font-bold mb-3">Default economics</h2>
        <p className="text-muted text-sm leading-relaxed mb-4">
          Every new Hearth starts with the 1/1/98 default: 1% Sparkz treasury
          (compute upkeep), 1% community pool (backers claim at splits.org), 98% creator
          distribution wallet (routes through 0xSplits to collaborators). Fully
          adjustable. Must sum to 100 and pass the extraction test.
        </p>
        <div className="flex h-4 w-full overflow-hidden rounded-full border border-border mb-3">
          <div className="bg-accent" style={{ width: "98%" }} />
          <div className="bg-foreground/40" style={{ width: "1%" }} />
          <div className="bg-muted/30" style={{ width: "1%" }} />
        </div>
        <div className="grid grid-cols-3 gap-2 text-xs">
          <div>
            <span className="text-accent font-bold">98%</span>
            <span className="text-muted ml-1">creator</span>
          </div>
          <div>
            <span className="text-foreground font-bold">1%</span>
            <span className="text-muted ml-1">community</span>
          </div>
          <div>
            <span className="text-muted font-bold">1%</span>
            <span className="text-muted ml-1">treasury</span>
          </div>
        </div>
        <p className="text-xs text-muted mt-3">
          Use the{" "}
          <Link href="/split-wizard" className="text-accent hover:underline">
            split wizard
          </Link>{" "}
          to tune your split for your specific situation.
        </p>
      </section>

      {/* CTAs */}
      <section className="flex flex-wrap gap-3">
        <Link
          href="/start"
          className="btn-spark px-5 py-2.5 text-sm font-semibold rounded-lg"
        >
          🔥 Open a Hearth
        </Link>
        <Link
          href="/explore"
          className="px-5 py-2.5 text-sm border border-border rounded-lg text-muted hover:text-foreground hover:border-border/80 transition-colors"
        >
          🔍 Browse Hearths
        </Link>
        <Link
          href="/community-pool"
          className="px-5 py-2.5 text-sm border border-border rounded-lg text-muted hover:text-foreground hover:border-border/80 transition-colors"
        >
          📊 Economics
        </Link>
        <Link
          href="/split-wizard"
          className="px-5 py-2.5 text-sm border border-border rounded-lg text-muted hover:text-foreground hover:border-border/80 transition-colors"
        >
          Split wizard
        </Link>
      </section>
    </main>
  );
}
